RocketHideout_B1F_MapScripts::
	.byte 0

RocketHideout_B1F_EventScript_RocketGruntHideout1::
	trainerbattle_single TRAINER_ROCKET_GRUNT_HIDEOUT_1, RocketHideout_B1F_Text_RocketGruntHideout1Intro, RocketHideout_B1F_Text_RocketGruntHideout1Defeat
	msgbox RocketHideout_B1F_Text_RocketGruntHideout1PostBattle, MSGBOX_AUTOCLOSE
	end

RocketHideout_B1F_EventScript_RocketGruntHideout2::
	trainerbattle_single TRAINER_ROCKET_GRUNT_HIDEOUT_2, RocketHideout_B1F_Text_RocketGruntHideout2Intro, RocketHideout_B1F_Text_RocketGruntHideout2Defeat
	msgbox RocketHideout_B1F_Text_RocketGruntHideout2PostBattle, MSGBOX_AUTOCLOSE
	end

RocketHideout_B1F_EventScript_RocketGruntHideout3::
	trainerbattle_single TRAINER_ROCKET_GRUNT_HIDEOUT_3, RocketHideout_B1F_Text_RocketGruntHideout3Intro, RocketHideout_B1F_Text_RocketGruntHideout3Defeat
	msgbox RocketHideout_B1F_Text_RocketGruntHideout3PostBattle, MSGBOX_AUTOCLOSE
	end

RocketHideout_B1F_EventScript_RocketGruntHideout4::
	trainerbattle_single TRAINER_ROCKET_GRUNT_HIDEOUT_4, RocketHideout_B1F_Text_RocketGruntHideout4Intro, RocketHideout_B1F_Text_RocketGruntHideout4Defeat
	msgbox RocketHideout_B1F_Text_RocketGruntHideout4PostBattle, MSGBOX_AUTOCLOSE
	end

RocketHideout_B1F_EventScript_RocketGruntHideout5::
	trainerbattle_single TRAINER_ROCKET_GRUNT_HIDEOUT_5, RocketHideout_B1F_Text_RocketGruntHideout5Intro, RocketHideout_B1F_Text_RocketGruntHideout5Defeat
	msgbox RocketHideout_B1F_Text_RocketGruntHideout5PostBattle, MSGBOX_AUTOCLOSE
	end

RocketHideout_B1F_EventScript_RocketGruntHideout6::
	trainerbattle_single TRAINER_ROCKET_GRUNT_HIDEOUT_6, RocketHideout_B1F_Text_RocketGruntHideout6Intro, RocketHideout_B1F_Text_RocketGruntHideout6Defeat
	msgbox RocketHideout_B1F_Text_RocketGruntHideout6PostBattle, MSGBOX_AUTOCLOSE
	end


RocketHideout_B1F_Text_RocketGruntHideout1Intro:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout1Defeat:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout1PostBattle:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout2Intro:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout2Defeat:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout2PostBattle:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout3Intro:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout3Defeat:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout3PostBattle:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout4Intro:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout4Defeat:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout4PostBattle:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout5Intro:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout5Defeat:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout5PostBattle:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout6Intro:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout6Defeat:
	.string "oh?$"

RocketHideout_B1F_Text_RocketGruntHideout6PostBattle:
	.string "oh?$"